### ISSUE TITLE
Support validity period selection in years

### ISSUE THREAD

**Issue by cdorros** [Netflix/lemur#195]
Some CAs (DigiCert is one) only allow you to specify validity periods in integers (1, 2 or 3 years). There are no specific date selections allowed. Would be nice if there was a way in the GUI to quickly select one of these options. Implementation flexible.

**Comment by kevgliss** [comment]
Verisign/Symantec does something similar but they do allow for the ability to specify the end date. Does digicert disallow a given end date at all?

https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_verisign/plugin.py#L100

**Comment by cdorros** [comment]
So after reviewing the API they do support a specific end-date if you want to end it earlier that the standard 1,2,3 years. Suppose this is is more of a usability request. Right now we're having to select dates that fall into the 1/2 year bounds. Would be nice to be able to select an integer 1 or 2 or 3.

**Comment by kevgliss** [comment]
Got it. UI wise I think we could do a dropdown with 1, 2, 3 years and then an advanced box for users who want to specify an end date.

**Comment by cdorros** [comment]
That would be perfect!

**Comment by kevgliss** [comment]
Sorry for the lag time... 

I believe the referenced commit should close this issue. Essentially I added a year drop down to the UI and then made the value of that dropdown visible via the issuer_options dict. Now individual plugins can have what they need to support number of years instead of specific beginning and end dates.

Feel free to comment on the PR. 

An example of the field in question:
<img width="879" alt="screen shot 2016-04-01 at 2 27 02 pm" src="https://cloud.githubusercontent.com/assets/2262214/14220679/709c44fe-f816-11e5-8c26-f61f182291fb.png">
