### ISSUE TITLE
Advice on using roles in Lemur.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#225]
We are integrating Lemur with our CI/CD pipeline (Jenkins) for the services that run in our Kubernetes AWS environment.  We'd like to get some advice on how to make our build process secure.  Would our Jenkins have a specific role/user token or user/pass to use against Lemur?  Or would each service have its own user in Lemur?  Would you advice to use the developers identity on the commit to pass the credentials to Lemur assuming that Lemur can talk SAML or OpenID or some other IDP.  Both Jenkins and AWS have SAML integration so we assume that the developers identity can be used to communicate with those parts of the infrastructure.  We are not sure how this works for Kubernetes yet though so we simple have the auth token committed to our private git repo.

**Comment by kevgliss** [comment]
I think it really depends on what you would like to control, do you want to limit which CA a user/role could use? Do you want to have attribution to certificates created? Both?

We do most things around our SSO. SSO allows us to authenticate the user and which groups they are members of. Within Lemur we take every group and create a corresponding role for it, effectively mapping groups to roles.This is in addition to some other standard roles (admin, user).  Roles are pretty flexible in Lemur. They currently dictate things like who can see what private keys, who can use/view authorities and if they can make any administrative actions. The mapping allows our most common use case: A user creates a certificate for team "A", everyone on team "A" should have access to it because they are in group "A".

In addition to our SSO created users/roles, we create "system users" that are essentially user/password combinations or long lived API tokens. These are typically used for API users where the SSO paradigm doesn't really work (server to server communication and scripting).

The systems needed to protect these credentials is outside of the scope of Lemur, but should be encrypted depending on their sensitivity (i.e. can they see all your private keys?)

I'm not sure which OpenID provider you are using, but adding support should be fairly straightforward. We recently had a PR that added support for Google OpenID without very much code.
