### ISSUE TITLE
Lemur to implement OCSP?

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#244]
Is there a way to use OCSP against to Lemur API in order to check if the certificate has been marked as inactive?  If not, is there a plan to implement such API?  Our issue is that we create a new certificate on every service change deploy because we need the destination plugin to ensure the existence of the corresponding Kubernetes secret.  Since the plugin is not executed on the certificate updates, we'd like the services themselves to be able to tell if the certificate used has been marked as inactive.

**Comment by kevgliss** [comment]
> Is there a way to use OCSP against to Lemur API in order to check if the certificate has been marked as inactive? If not, is there a plan to implement such API?

I don't think there currently an API for that. If you just want an unauthenticated endpoint that will give you 'active' or 'inactive'. That would be fairly straightforward to add to the certificate [views](https://github.com/Netflix/lemur/blob/master/lemur/certificates/views.py#L551).

I would suggest adding an new endpoint that would allow you post a certificate (pem format probably) and would return ['active', 'inactive', 'unknown']. 

We don't have any currently plans to create such an API, but would be open to the idea of pulling it in. 

> Our issue is that we create a new certificate on every service change deploy because we need the destination plugin to ensure the existence of the corresponding Kubernetes secret. 

I am not totally clear on what you are trying to do here, is the certificate encrypted with a kubernetes secret when generated?

> Since the plugin is not executed on the certificate updates, we'd like the services themselves to be able to tell if the certificate used has been marked as inactive.

Which plugin are you referring to, any authority plugin? a destination plugin? Are you describing some additional actions being taken when a certificate is marked as inactive?

**Comment by mik373** [comment]
The plugin is a destination plugin and ideally I'd like to have an option of it being called if a PUT is called on the certificate that has such destination.

Since you did not have plans for OCSP, how do you envision certificate revocation procedure for non-expired certificates for the certs managed by Lemur?

**Comment by kevgliss** [comment]
Well, remember that Lemur is not a CA... typically the CA will manage the revocation process (via OCSP or CRL). Since *I think* you are using openssl to shoehorn Lemur into being a CA. I would suggest you stand up your own OCSP responder (http://isrlabs.net/wordpress/?p=169) and simply modify the NGINX configuration to alias it to a relevant route. In this way it would be able to be able to run side-by-side Lemur (with the same DNS even).

You would still need to figure out how you want to revoke those certificates. Lemur does not have this facility (not a CA) and will not in the future. 

Updating wise it sounds like you are looking for something like #65 that would allow a destination plugin to take an action when it is no longer associated with a certificate (via PUT) this has been on the roadmap but hadn't been prioritized at the moment. This functionality could perhaps be used by your plugin to revoke the certificate upon dissociation.
