### ISSUE TITLE
ADCS Plugin :: ADCS Web enrollment deprecation

### ISSUE THREAD

**Issue by Sudhakargen** [Netflix/lemur#2863]
Lemur ADCS plugin uses ADCS Web enrollment for performing certificate management (certsrv). And I learn that Microsoft ADCS web enrollment is outdated and probably deprecated. Can you please let me know if there is any alternate for ADCS Web enrollment that Lemur already/plans to provides.
 

Thanks,
Sudhakar

**Comment by hosseinsh** [comment]
ADCS plugin is a community contribution.
@sirferl might be able to better comment on this, as he wrote the plugin.

**Comment by sirferl** [comment]
@Sudhakargen : I was not aware of that deprecation. I will investigate, if there is a way to integrate lemur after the turn off of ADCS Web enrollment.
regards sirferl

**Comment by Sudhakargen** [comment]
Thanks for your reply @sirferl and @hosseinsh . I couldn't find any Microsoft documentation that said it is deprecated(your right there). However, after checking with Security team with whom I work with I was told that ADCS is blocked as a policy from the point of view of security. We use Windows Server 2016. So as a result I cannot use Lemur's ADCS plugin. Currently I'm checking Microsoft documentation for alternates (REST API or Powershell).
Thanks again.

**Comment by Sudhakargen** [comment]
Microsoft provides a REST API as follows https://docs.microsoft.com/en-us/microsoft-identity-manager/reference/certificate-management-rest-api-service-details

Sure, will get back.

**Comment by sirferl** [comment]
@Sudhakargen I will look into it, but cannot give you a precise time frame.

**Comment by sirferl** [comment]
@Sudhakargen : After reading through the doc in the link you provided, I understand that this is for the Microsoft Identity Manager (we do not currently use it). I retraced my former investigations in that case and found the API for ADCS. https://docs.microsoft.com/en-us/windows/win32/seccertenroll/certenroll-portal
As you can see there, it is not a web based API but a .DLL based set of calls. That's why I had to resort to using the (arkward) web based Interface.
As always: If I understood something wrong, please correct me.

**Comment by sirferl** [comment]
@Sudhakargen , @hosseinsh : hello, if the information I gave on October 7th is sufficient, I suggest this ticket should be closed.
thank you

**Comment by Sudhakargen** [comment]
Please go ahead and close this request. Thanks again.

**Comment by sirferl** [comment]
@hosseinsh : Hi hossein, could you please close this issue. There is nothing to do.

**Comment by hosseinsh** [comment]
Thanks @sirferl, closing the issue.
