### ISSUE TITLE
3 email expiry notifications for a single cert

### ISSUE THREAD

**Issue by ramavulloju** [Netflix/lemur#3587]
Hello, I am seeing 3 email expiry notifications for single cert. let me know if i can make any edits to messaging.py to fix the issue or any other solution? Thank you so much for your help!

**Comment by jtschladen** [comment]
Hi @ramavulloju - could you please clarify a couple details?

1. The email address that is receiving the multiple notifications - is it configured as `LEMUR_SECURITY_TEAM_EMAIL`? Is it used in a configured notification (or multiple)? Is it the certificate owner?
2. Which version of Lemur are you running?

**Comment by ramavulloju** [comment]
Hello Jasmine,

Please find my responses below.

1. The email address that is receiving the multiple notifications - is it configured as LEMUR_SECURITY_TEAM_EMAIL? Is it used in a configured notification (or multiple)? Is it the certificate owner?
      No. It is not configured as LEMUR_SECURITY_TEAM_EMAIL.  It is a certificate owner.
2. Which version of Lemur are you running?
      I am using the version - = "0.7.0". i could see this in lemur/__about__.py.

Thank you!

**Comment by ramavulloju** [comment]
Hi @jtschladen any thoughts?

**Comment by jtschladen** [comment]
@ramavulloju I'm not aware of any bugs that would cause that issue if it's just the certificate owner. You probably want to check and confirm that it's not configured for multiple duplicate notifications in the Lemur UI, as that would result in duplicate emails.

0.7.0 is fairly old, though, and there have been a number of notification bugs fixed since then, so upgrading to the [latest release](https://github.com/Netflix/lemur/releases/latest) (0.9.0 currently) _may_ help (though I can't guarantee that, since it's not possible for me to tell exactly what's going wrong with your setup currently).

**Comment by ramavulloju** [comment]
Sure @jtschladen  I will try the upgrade. Thanks for your help!
