### ISSUE TITLE
Installation error (lemur 0.9.0, ubuntu 20.04, python 3.7)

### ISSUE THREAD

**Issue by mced** [Netflix/lemur#3628]
Hello,

I'm trying installing lemur 0.9.0 (from GitHub release) on Ubuntu 20.04 & python 3.7 but I have the following error when running `make release` which seems legit to me:

```
                  [16:35:06] 'dev:styles' errored after 16 ms
                  [16:35:06] Error: File not found with singular glob: /www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/loading-bar.css (if this was purposeful, use `allowEmpty` option)
                      at Glob.<anonymous> (/www/lemur/lemur-0.9.0/node_modules/glob-stream/readable.js:84:17)
                      at Object.onceWrapper (events.js:286:20)
                      at Glob.emit (events.js:198:13)
                      at Glob.EventEmitter.emit (domain.js:448:20)
                      at Glob._finish (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:195:8)
                      at done (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:180:14)
                      at Glob._processSimple2 (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:686:12)
                      at /www/lemur/lemur-0.9.0/node_modules/glob/glob.js:674:10
                      at Glob._stat2 (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:770:12)
                      at lstatcb_ (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:762:12)
                      at RES (/www/lemur/lemur-0.9.0/node_modules/inflight/inflight.js:31:16)
                      at f (/www/lemur/lemur-0.9.0/node_modules/once/once.js:25:25)
                      at FSReqWrap.oncomplete (fs.js:153:21)
                  [16:35:06] 'build:inject' errored after 17 ms
                  [16:35:06] 'build:html' errored after 17 ms
                  [16:35:06] 'build' errored after 126 ms
```

```
$ ls -alh /www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/loading-bar.css
ls: cannot access '/www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/loading-bar.css': No such file or directory
$ ls -alh /www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/
ls: cannot access '/www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/': No such file or directory
$ ls -alh /www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/
total 36K
drwxr-xr-x  2 lemur lemur 4.0K Jun  9 16:42 .
drwxr-xr-x 39 lemur lemur 4.0K Jun  9 16:34 ..
-rw-r--r--  1 lemur lemur  932 Jun  9 16:34 .bower.json
-rw-r--r--  1 lemur lemur 4.0K Jun 19  2015 CHANGELOG.md
-rw-r--r--  1 lemur lemur 2.2K Jun 19  2015 Gruntfile.js
-rw-r--r--  1 lemur lemur 1.1K Jun 19  2015 LICENSE
-rw-r--r--  1 lemur lemur 6.8K Jun 19  2015 README.md
-rw-r--r--  1 lemur lemur  550 Jun  3 16:43 bower.json
```

Do you have some insight to help me to complete the install? Thanks.

**Comment by hosseinsh** [comment]
Hi @mced, unfortunately I haven't used the `make release` option, so my experience is a bit limited. 

You might want to check if `bower` is installed.


```
# macOS
brew install postgresql
brew install node@10 # if you already have node 12+ installed it will need to be unlinked using below command
brew link --overwrite node@10 --force # OR you can use nvm
brew install python3
brew install python-dev
npm install npm@latest
npm install gulp-cli -g
npm install gulp -D
npx -p touch nodetouch gulpfile.js
npm install -g bower
bower install

export LEMURDEV=~/lemur-dev && mkdir $LEMURDEV && cd $LEMURDEV

python3.7 -m venv $LEMURDEV && source $LEMURDEV/bin/activate
cd $LEMURDEV &&  pip3 install -e ./lemur

# starting the backend
cd $LEMURDEV/lemur
LEMUR_CONF={you-config-file} python lemur/manage.py runserver -p 8000

# starting the front end:
gulp serve
```

**Comment by mced** [comment]
Hi @hosseinsh 

In fact it's when I run `gulp build` that generates that error... any clue?

```
$ node_modules/.bin/bower -v
1.8.12

$ node_modules/.bin/gulp build
[06:45:13] Using gulpfile /www/lemur/lemur-0.9.0/gulpfile.js
[06:45:14] Starting 'build'...
[06:45:14] Starting 'build:images'...
[06:45:14] Finished 'build:images' after 26 ms
[06:45:14] Starting 'build:fonts'...
[06:45:14] Starting 'dev:fonts'...
[06:45:14] Finished 'dev:fonts' after 38 ms
[06:45:14] Starting '<anonymous>'...
[06:45:14] Finished '<anonymous>' after 30 ms
[06:45:14] Finished 'build:fonts' after 70 ms
[06:45:14] Starting 'build:html'...
[06:45:14] Starting 'build:inject'...
[06:45:14] Starting 'dev:styles'...
[06:45:14] 'dev:styles' errored after 16 ms
[06:45:14] Error: File not found with singular glob: /www/lemur/lemur-0.9.0/bower_components/angular-loading-bar/src/loading-bar.css (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/www/lemur/lemur-0.9.0/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:195:8)
    at done (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:180:14)
    at Glob._processSimple2 (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:686:12)
    at /www/lemur/lemur-0.9.0/node_modules/glob/glob.js:674:10
    at Glob._stat2 (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:770:12)
    at lstatcb_ (/www/lemur/lemur-0.9.0/node_modules/glob/glob.js:762:12)
    at RES (/www/lemur/lemur-0.9.0/node_modules/inflight/inflight.js:31:16)
    at f (/www/lemur/lemur-0.9.0/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:21)
[06:45:14] 'build:inject' errored after 20 ms
[06:45:14] 'build:html' errored after 21 ms
[06:45:14] 'build' errored after 122 ms
```

**Comment by mced** [comment]
@hosseinsh Can you help me pinpoint how to debug this?
I tried the latest v0.10.0 and I got the same result.
I saw that you removed ubuntu 20.04 from Travis, is that mean that lemur is intended to be installed on ubuntu18.04?

Here is the version of the tools on my setup:
```bash
(venv) lemur@lemur:/www/lemur/lemur$ python -V
Python 3.8.10
(venv) lemur@lemur:/www/lemur/lemur$ npm -v
6.14.4
(venv) lemur@lemur:/www/lemur/lemur$ node -v
v10.19.0
(venv) lemur@lemur:/www/lemur/lemur$ node_modules/.bin/gulp -v
CLI version: 2.3.0
Local version: 4.0.2
(venv) lemur@lemur:/www/lemur/lemur$ node_modules/.bin/bower -v
1.8.12
```

**Comment by mced** [comment]
I managed to pass the installation BUT I needed to add `{ allowEmpty: true }` in `gulp/buid.js` at line 112. 

```bash
diff --git a/gulp/build.js b/gulp/build.js
index 13915051..8ee0420b 100644
--- a/gulp/build.js
+++ b/gulp/build.js
@@ -109,7 +109,7 @@ gulp.task('dev:styles', function () {
     'lemur/static/app/styles/lemur.css'
   ];

-  return gulp.src(fileList)
+  return gulp.src(fileList, { allowEmpty: true })
     .pipe(gulpif(isBootswatchFile, foreach(function (stream, file) {
       let themeName = path.basename(path.dirname(file.path)),
         content = replaceAll(baseContent, '$theme$', themeName);
```


```javascript
let fileList = [
    'bower_components/bootswatch/sandstone/bootswatch.less',
    'bower_components/fontawesome/css/font-awesome.css',
    'bower_components/angular-chart.js/dist/angular-chart.css',
    'bower_components/angular-loading-bar/src/loading-bar.css',
    'bower_components/angular-ui-switch/angular-ui-switch.css',
    'bower_components/angular-wizard/dist/angular-wizard.css',
    'bower_components/ng-table/dist/ng-table.css',
    'bower_components/angularjs-toaster/toaster.css',
    'bower_components/angular-ui-select/dist/select.css',
    'lemur/static/app/styles/lemur.css'
  ];
```
On the above list; there are two missing files on the filesystem:
```bash
lemur@lemur:/www/lemur/lemur$ ls bower_components/angular-loading-bar/src/loading-bar.css
ls: cannot access 'bower_components/angular-loading-bar/src/loading-bar.css': No such file or directory
lemur@lemur:/www/lemur/lemur$ ls bower_components/angularjs-toaster/toaster.css
ls: cannot access 'bower_components/angularjs-toaster/toaster.css': No such file or directory
```

**Comment by charhate** [comment]
Hi @mced, I see the PR is still marked as a draft. Sorry if I'm commenting too soon. Though `{ allowEmpty: true }` makes it work, these css files are needed for rendering and functioning of lemur UI. So I believe finding why the css files are missing is the right move. It should work fine for Ubuntu 20.04, the reason of removing it form travis was the broken dependencies of clang-10 (#3544)

- Command `make release` seems to perform `npm install` which should download the two files from above error message. I typically run `make` followed by `gulp build` or `gulp serve`. Can you give it a try from `/www/lemur/lemur/` directory. 
- If you try `npm install angularjs-toaster`, does that work?
-  does `npm config get registry` returns `https://registry.npmjs.org/`

**Comment by mced** [comment]
Hello @charhate, thanks for your tips, except that I'm still confused...

> does npm config get registry returns https://registry.npmjs.org/

Yes, it does.
```bash
(venv) lemur@lemur:/www/lemur/lemur$ npm config get registry
http://registry.npmjs.org/
```

> Command `make release` seems to perform `npm install` which should download the two files from above error message. I typically run `make` followed by `gulp build` or `gulp serve`. Can you give it a try from `/www/lemur/lemur/` directory.

The result is the same as my previous comment, except that the path points to `lemur-0.10.0` instead of `lemur-0.9.0` as `/www/lemur/lemur` is a softlink to `/www/lemur/lemur-0.10.0`

```bash
node_modules/.bin/gulp build
[09:41:36] Using gulpfile /www/lemur/lemur-0.10.0/gulpfile.js
[09:41:36] Starting 'build'...
[09:41:36] Starting 'build:images'...
[09:41:36] Finished 'build:images' after 26 ms
[09:41:36] Starting 'build:fonts'...
[09:41:36] Starting 'dev:fonts'...
[09:41:36] Finished 'dev:fonts' after 37 ms
[09:41:36] Starting '<anonymous>'...
[09:41:36] Finished '<anonymous>' after 29 ms
[09:41:36] Finished 'build:fonts' after 68 ms
[09:41:36] Starting 'build:html'...
[09:41:36] Starting 'build:inject'...
[09:41:36] Starting 'dev:styles'...
[09:41:36] 'dev:styles' errored after 16 ms
[09:41:36] Error: File not found with singular glob: /www/lemur/lemur-0.10.0/bower_components/angular-loading-bar/src/loading-bar.css (if t
his was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/www/lemur/lemur-0.10.0/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:286:20)
    at Glob.emit (events.js:198:13)
    at Glob.EventEmitter.emit (domain.js:448:20)
    at Glob._finish (/www/lemur/lemur-0.10.0/node_modules/glob/glob.js:195:8)
    at done (/www/lemur/lemur-0.10.0/node_modules/glob/glob.js:180:14)
    at Glob._processSimple2 (/www/lemur/lemur-0.10.0/node_modules/glob/glob.js:686:12)
    at /www/lemur/lemur-0.10.0/node_modules/glob/glob.js:674:10
    at Glob._stat2 (/www/lemur/lemur-0.10.0/node_modules/glob/glob.js:770:12)
    at lstatcb_ (/www/lemur/lemur-0.10.0/node_modules/glob/glob.js:762:12)
    at RES (/www/lemur/lemur-0.10.0/node_modules/inflight/inflight.js:31:16)
    at f (/www/lemur/lemur-0.10.0/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:21)
[09:41:36] 'build:inject' errored after 19 ms
[09:41:36] 'build:html' errored after 20 ms
[09:41:36] 'build' errored after 118 ms
make: *** [Makefile:29: release] Error 1
```

```bash
(venv) lemur@lemur:/www/lemur/lemur$ ls -alh bower_components/angular-loading-bar/
total 36K
drwxr-xr-x  2 lemur lemur 4.0K Aug  4 09:41 .
drwxrwxr-x 39 lemur lemur 4.0K Aug  4 09:41 ..
-rw-r--r--  1 lemur lemur  932 Aug  4 09:41 .bower.json
-rw-r--r--  1 lemur lemur 4.0K Jun 19  2015 CHANGELOG.md
-rw-r--r--  1 lemur lemur 2.2K Jun 19  2015 Gruntfile.js
-rw-r--r--  1 lemur lemur 1.1K Jun 19  2015 LICENSE
-rw-r--r--  1 lemur lemur 6.8K Jun 19  2015 README.md
-rw-r--r--  1 lemur lemur  550 Jun  3 16:43 bower.json
(venv) lemur@lemur:/www/lemur/lemur$ ls -alh bower_components/angularjs-toaster/
total 48K
drwxr-xr-x  2 lemur lemur 4.0K Aug  4 09:41 .
drwxrwxr-x 39 lemur lemur 4.0K Aug  4 09:41 ..
-rw-r--r--  1 lemur lemur  600 Aug  4 09:41 .bower.json
-rw-r--r--  1 lemur lemur 1.1K Jan 19  2016 LICENSE
-rw-r--r--  1 lemur lemur  11K Jan 19  2016 README.md
-rw-r--r--  1 lemur lemur  260 Jan 19  2016 bower.json
-rw-r--r--  1 lemur lemur   53 Jan 19  2016 index.js
-rw-r--r--  1 lemur lemur 1.9K Jan 19  2016 karma.conf.js
-rw-r--r--  1 lemur lemur  717 Jan 19  2016 karma.coverage.js
-rw-r--r--  1 lemur lemur  715 Jan 19  2016 package.json
```

But what I found is quite interesting; after using `make release`, or `make`, I found the needed `angular-loading-bar` and `angularjs-toaster` files under `node_modules` directory instead of `bower_components`.

```bash
(venv) lemur@lemur:/www/lemur/lemur$ ls -alh node_modules/angular-loading-bar/
total 108K
drwxrwxr-x   6 lemur lemur 4.0K Aug  4 10:02 .
drwxrwxr-x 908 lemur lemur  36K Aug  4 10:03 ..
-rw-rw-r--   1 lemur lemur  415 Jan  5  2015 .editorconfig
-rw-rw-r--   1 lemur lemur 5.8K Jan  5  2015 .jshintrc
-rw-rw-r--   1 lemur lemur   44 Jan  5  2015 .npmignore
-rw-rw-r--   1 lemur lemur 4.0K Jun 19  2015 CHANGELOG.md
-rw-rw-r--   1 lemur lemur 2.2K Jan  5  2015 Gruntfile.js
-rw-rw-r--   1 lemur lemur 1.1K Jan  5  2015 LICENSE
-rw-rw-r--   1 lemur lemur 6.8K Jun 19  2015 README.md
-rw-rw-r--   1 lemur lemur  550 Jun 19  2015 bower.json
drwxrwxr-x   2 lemur lemur 4.0K Aug  4 10:02 build
drwxrwxr-x   2 lemur lemur 4.0K Aug  4 10:02 example
-rw-rw-r--   1 lemur lemur   72 Jun 19  2015 index.js
-rw-rw-r--   1 lemur lemur 1.8K Aug  4 10:02 package.json
drwxrwxr-x   2 lemur lemur 4.0K Aug  4 10:02 src
drwxrwxr-x   2 lemur lemur 4.0K Aug  4 10:02 test
(venv) lemur@lemur:/www/lemur/lemur$ ls -alh node_modules/angularjs-toaster/
total 172K
drwxrwxr-x   3 lemur lemur 4.0K Aug  4 10:02 .
drwxrwxr-x 908 lemur lemur  36K Aug  4 10:03 ..
-rw-rw-r--   1 lemur lemur   81 Jan 20  2016 .npmignore
-rw-rw-r--   1 lemur lemur  518 Jan 20  2016 .travis.yml
-rw-rw-r--   1 lemur lemur 1.1K Jan 20  2016 LICENSE
-rw-rw-r--   1 lemur lemur  11K Jan 20  2016 README.md
-rw-rw-r--   1 lemur lemur  277 Jan 20  2016 bower.json
-rw-rw-r--   1 lemur lemur   55 Jan 20  2016 index.js
-rw-rw-r--   1 lemur lemur 1.9K Jan 20  2016 karma.conf.js
-rw-rw-r--   1 lemur lemur  754 Jan 20  2016 karma.coverage.js
-rw-rw-r--   1 lemur lemur 1.6K Aug  4 10:02 package.json
drwxrwxr-x   2 lemur lemur 4.0K Aug  4 10:02 test
-rw-rw-r--   1 lemur lemur  13K Jan 20  2016 toaster.css
-rw-rw-r--   1 lemur lemur  26K Jan 20  2016 toaster.js
-rw-rw-r--   1 lemur lemur  11K Jan 20  2016 toaster.min.css
-rw-rw-r--   1 lemur lemur 7.7K Jan 20  2016 toaster.min.js
-rw-rw-r--   1 lemur lemur  14K Jan 20  2016 toaster.scss
```

Does this allow you to understand what is going on?
I doubt I'm the only one as I'm using an Ubuntu 20.04 vanilla instance.

**Comment by charhate** [comment]
Hi @mced, thanks for sharing details. My experience with bower is limited, so trying to breakdown the steps and hoping it helps us to go in right direction.

For me, node_modules does not have `angular-loading-bar` and `angularjs-toaster` (I believe that's true for everything under `bower_components`). That makes me think these are installed with npm for you instead of bower? Running `npm install angularjs-toaster` gets it in `node_modules` directory.

Can you try

- Run `bower install angular-loading-bar#0.8.0` and see if that makes `gulp build` work (not a solution, trying to narrow down the issue). I deleted `angular-loading-bar` and `angularjs-toaster` and tried bower install. Note that it got both, `angular-loading-bar#0.8.0 bower_components/angular-loading-bar` and
`angularjs-toaster#1.0.0 bower_components/angularjs-toaster`.

`(lemur-dev) sayalicharhate@MacBook-Pro lemur % gulp build
[18:21:33] Using gulpfile ~/Git/lemur-dev/lemur/gulpfile.js
[18:21:33] Starting 'build'...
.
.
[18:21:33] Starting 'dev:styles'...
[18:21:33] 'dev:styles' errored after 8.76 ms
[18:21:33] Error: File not found with singular glob: /Users/sayalicharhate/Git/lemur-dev/lemur/bower_components/angular-loading-bar/src/loading-bar.css (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/sayalicharhate/Git/lemur-dev/lemur/node_modules/glob-stream/readable.js:84:17)
.
.
.
[18:21:33] 'build' errored after 79 ms
(lemur-dev) sayalicharhate@MacBook-Pro lemur % bower install angular-loading-bar#0.8.0
bower angular-loading-bar#~0.8.0           cached https://github.com/chieffancypants/angular-loading-bar.git#0.8.0
bower angular-loading-bar#~0.8.0         validate 0.8.0 against https://github.com/chieffancypants/angular-loading-bar.git#~0.8.0
bower angular-loading-bar#0.8.0            cached https://github.com/chieffancypants/angular-loading-bar.git#0.8.0
bower angular-loading-bar#0.8.0          validate 0.8.0 against https://github.com/chieffancypants/angular-loading-bar.git#0.8.0
bower angularjs-toaster#~1.0.0             cached https://github.com/jirikavi/AngularJS-Toaster.git#1.0.0
bower angularjs-toaster#~1.0.0           validate 1.0.0 against https://github.com/jirikavi/AngularJS-Toaster.git#~1.0.0
bower angular-loading-bar#0.8.0           install angular-loading-bar#0.8.0
bower angularjs-toaster#~1.0.0            install angularjs-toaster#1.0.0

angular-loading-bar#0.8.0 bower_components/angular-loading-bar
└── angular#1.4.9

angularjs-toaster#1.0.0 bower_components/angularjs-toaster
├── angular#1.4.9
└── angular-animate#1.4.14

(lemur-dev) sayalicharhate@MacBook-Pro lemur % gulp build                             
[18:21:48] Using gulpfile ~/Git/lemur-dev/lemur/gulpfile.js
[18:21:48] Starting 'build'...
.
.
.
[18:21:50] Finished 'build' after 2.24 s
(lemur-dev) sayalicharhate@MacBook-Pro lemur % `

- Delete `bower_components` directory, and run `make`. The output that I saw (copied only relevant details) is as below.

`
--> Installing git hooks
if [ -d .git/hooks ]; then \
		git config branch.autosetuprebase always; \
		cd .git/hooks && ln -sf ../../hooks/* ./; \
	fi

--> Installing dependencies
npm install

> Lemur@ postinstall /Users/sayalicharhate/Git/lemur-dev/lemur
> bower install --allow-root --config.interactive=false

bower angularjs-toaster#~1.0.0  cached https://github.com/jirikavi/AngularJS-Toaster.git#1.0.0
bower angularjs-toaster#~1.0.0         validate 1.0.0 against https://github.com/jirikavi/AngularJS-Toaster.git#~1.0.0
.... many such.....

bower angularjs-toaster#~1.0.0          install angularjs-toaster#1.0.0
bower json3#~3.3                        install json3#3.3.2
.... many such.....

angularjs-toaster#1.0.0 bower_components/angularjs-toaster
├── angular#1.4.9
└── angular-animate#1.4.14

json3#3.3.2 bower_components/json3

restangular#1.5.2 bower_components/restangular
├── angular#1.4.9
└── lodash#2.4.2
.... many such.....

pip install -e 
.
.
node_modules/.bin/gulp build
`

Do you see other bower components installed, e.g. `bower_components/json3`? This is what I see 
`(lemur-dev) sayalicharhate@MacBook-Pro lemur % ls -lh bower_components
total 0
drwxr-xr-x  16 sayalicharhate  staff   512B Aug  4 17:43 Chart.js
drwxr-xr-x  12 sayalicharhate  staff   384B Aug  4 17:43 angular
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 angular-animate
drwxr-xr-x  14 sayalicharhate  staff   448B Aug  4 17:43 angular-bootstrap
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 angular-chart.js
drwxr-xr-x   6 sayalicharhate  staff   192B Aug  4 17:43 angular-clipboard
drwxr-xr-x  12 sayalicharhate  staff   384B Aug  4 17:43 angular-file-saver
drwxr-xr-x  12 sayalicharhate  staff   384B Aug  4 18:03 angular-loading-bar
drwxr-xr-x  21 sayalicharhate  staff   672B Aug  4 17:43 angular-moment
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 angular-sanitize
drwxr-xr-x  14 sayalicharhate  staff   448B Aug  4 17:43 angular-smart-table
drwxr-xr-x  22 sayalicharhate  staff   704B Aug  4 17:43 angular-strap
drwxr-xr-x   7 sayalicharhate  staff   224B Aug  4 17:43 angular-translate
drwxr-xr-x  10 sayalicharhate  staff   320B Aug  4 17:43 angular-ui-router
drwxr-xr-x  14 sayalicharhate  staff   448B Aug  4 17:43 angular-ui-select
drwxr-xr-x  13 sayalicharhate  staff   416B Aug  4 17:43 angular-ui-switch
drwxr-xr-x   8 sayalicharhate  staff   256B Aug  4 17:43 angular-underscore
drwxr-xr-x  16 sayalicharhate  staff   512B Aug  4 17:43 angular-wizard
drwxr-xr-x  16 sayalicharhate  staff   512B Aug  4 18:03 angularjs-toaster
drwxr-xr-x   8 sayalicharhate  staff   256B Aug  4 17:43 blob-polyfill
drwxr-xr-x  20 sayalicharhate  staff   640B Aug  4 17:43 bootstrap
drwxr-xr-x  26 sayalicharhate  staff   832B Aug  4 17:43 bootswatch
drwxr-xr-x   8 sayalicharhate  staff   256B Aug  4 17:43 d3
drwxr-xr-x  17 sayalicharhate  staff   544B Aug  4 17:43 es5-shim
drwxr-xr-x   7 sayalicharhate  staff   224B Aug  4 17:43 file-saver.js
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 font-awesome
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 fontawesome
drwxr-xr-x  10 sayalicharhate  staff   320B Aug  4 17:43 jquery
drwxr-xr-x   9 sayalicharhate  staff   288B Aug  4 17:43 json3
drwxr-xr-x   6 sayalicharhate  staff   192B Aug  4 17:43 lodash
drwxr-xr-x  12 sayalicharhate  staff   384B Aug  4 17:43 moment
drwxr-xr-x  11 sayalicharhate  staff   352B Aug  4 17:43 moment-range
drwxr-xr-x  22 sayalicharhate  staff   704B Aug  4 17:43 ng-table
drwxr-xr-x  12 sayalicharhate  staff   384B Aug  4 17:43 ngletteravatar
drwxr-xr-x  19 sayalicharhate  staff   608B Aug  4 17:43 restangular
drwxr-xr-x   9 sayalicharhate  staff   288B Aug  4 17:43 satellizer
drwxr-xr-x   9 sayalicharhate  staff   288B Aug  4 17:43 underscore`

**Comment by mced** [comment]
Thanks for your support @charhate.

I delete all directories related to `npm`, `bower` and `lemur`, and then `git clone` the branch instead of downloading the tarball:

```bash
(venv) lemur@lemur:/www/lemur$ rm -rf lemur-0.10.0/
(venv) lemur@lemur:/www/lemur$ rm -rf ~/.npm
(venv) lemur@lemur:/www/lemur$ rm -rf ~/.cache/
(venv) lemur@lemur:/www/lemur$ rm -rf ~/.config/
```

```bash
(venv) lemur@lemur:/www/lemur$ git clone --branch v0.10.0 git@github.com:Netflix/lemur.git lemur-0.10.0
Cloning into 'lemur-0.10.0'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
remote: Enumerating objects: 30364, done.
remote: Counting objects: 100% (564/564), done.
remote: Compressing objects: 100% (303/303), done.
remote: Total 30364 (delta 378), reused 407 (delta 259), pack-reused 29800
Receiving objects: 100% (30364/30364), 8.59 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (20954/20954), done.
Note: switching to 'c84fac6c1b75e5927b4b925c0fa30efce6b3819a'.
...
```

Good.

At this point, I don't have any `bower` binary installed, thus I run `make`... and **it worked without any error** :tada: I suspect that having npm cache made the installation failed...

Thank you again.

--
Now I'm facing a problem when I apply database migrations from a database coming from a `v0.6.0`. It looks to be stuck at `5770674184de` migration:

```bash
(venv) lemur@lemur:/www/lemur/lemur/lemur$ lemur db upgrade
...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5bc47fa7cac4 -> ce547319f7be, Add id column to certificate_notification_associations.
Adding id column
INFO  [alembic.runtime.migration] Running upgrade ce547319f7be -> 5770674184de, Remove duplicates from certificate_notification_associations.
Querying for all entries in certificate_notification_associations.
```

```psql
lemur=> SELECT
    datname, wait_event_type, wait_event, query
FROM pg_stat_activity
WHERE query_start < now() - '20 sec'::interval;
 datname | wait_event_type | wait_event |                                                                                                                                                           query                                                      
---------+-----------------+------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 lemur   | Client          | ClientRead | UPDATE alembic_version SET version_num='ce547319f7be' WHERE alembic_version.version_num = '5bc47fa7cac4'
 lemur   | Lock            | relation   | SELECT certificate_notification_associations.certificate_id AS certificate_notification_associations_certificate_id, certificate_notification_associations.notification_id AS certificate_notification_associations_notification_id, certificate_notification_associations.id AS certificate_notification_associations_id +
         |                 |            | FROM certificate_notification_associations
(2 rows)
```

I have 18432 rows in the `certificate_notification_associations` table.

**Comment by charhate** [comment]
@mced, glad you got it working. I will go ahead and close PR #3681 and also this issue.
