### ISSUE TITLE
Documentation for CertificateRevoke is incorrect 

### ISSUE THREAD

**Issue by evan-chaney** [Netflix/lemur#3662]
Looking at the docs under both [Latest](https://lemur.readthedocs.io/en/latest/developer/index.html#put--certificates-1-revoke) and [8.0](https://lemur.readthedocs.io/en/latest/developer/index.html#put--certificates-1-revoke), both show certificates/{id}/revoke as a POST in the example. In my testing against 8.0 this returned a 405 METHOD NOT ALLOWED.

The documentation is also not clear on what data should be send with the request and in what format. It shows data=None in the header right above where I linked: `put(certificate_id, data=None)` however if you actually don't pass any data the endpoint returns a 400: BAD REQUEST. There is no link to acceptable values for crlReason. I tried Googling and found [this page](https://docs.oracle.com/javase/7/docs/api/java/security/cert/CRLReason.html) and tried "UNSPECIFIED" but that also returns a 400: BAD REQUEST with message `{"message": "Validation Error.", "reasons": {"crlReason": "Not a valid choice."}}`.

Lastly even though comments is listed as `"comments": "Additional details if any"` - implying that it is optional - I could not get a successful revocation without supplying comments.

**Comment by charhate** [comment]
Hi @evan-chaney, thank you for bringing up the gap in documentation. I have made changes as per the suggestion.
1. The request type is changed to PUT in `Example request:`
2. The `crlReason` and `comments` are both optional, now specified so in the doc. You may want to pass `{}` since `Accept: application/json` for the endpoint. I could revoke with and without `crlReason` and/or `comments`. If you can please share the error that you see without supplying comments, I can take a look.
3. I have added link to acceptable values for `crlReason`

**Comment by evan-chaney** [comment]
I can confirm that supplying just `{}` for the data works. My error without `comments` was me not passing any data. The changes on the docs look good. Thanks for the quick response!
