### ISSUE TITLE
The `rotate_elbs` command is broken

### ISSUE THREAD

**Issue by mikegrima** [Netflix/lemur#442]
The `rotate_elbs` manager command is currently broken.

A stack trace that looks like this results:

```
  File "manage.py", line 604, in run
    elb.update_listeners(account_id, region, elb_name, [(from_port, to_port, protocol, arn)], [from_port])
AttributeError: 'module' object has no attribute 'update_listeners'
```

This was commented out in #336.  Was the functionality replaced or deprecated?

**Comment by kevgliss** [comment]
This was backed out because it wasn't quite ready. Initially we had support for managing ELBs directly (creating new elbs, listeners etc.,). This was removed to keep Lemur more focused on managing certificates. At some point in the near future we will be reviving this functionality and making it a first class citizen when the necessary code is written such that "monitored" endpoints will have their certificates re-issued and rotated. I would imagine you might be able to uncomment that old code and have it work with minor changes.
