### ISSUE TITLE
Post latest version in pypi

### ISSUE THREAD

**Issue by gesquive** [Netflix/lemur#675]
The latest package in pypi is [0.2.1](https://pypi.python.org/pypi/lemur/0.2.1), can we have the latest version (v0.4.0) posted as well?

**Comment by kevgliss** [comment]
So awhile back I tried very hard to publish this to pypi. However, I took the `lemur` namespace over from another library. That library had a version of >1.9 so now when tried to upload my package it get's rejected due to the fact that the version is still on 0.4.0. Even after deleting the entire package and trying, the problem persists. 

As noted it's listed as 0.2.1 but it never was actually available... 

It seems to me that the only path forward is to sufficiently bump Lemur's version to supersede the previous package or create a new package name. 

What is your use case for using pypi instead of simply running `git clone` and `git checkout <tag>`?

**Comment by gesquive** [comment]
If we `git clone` to get a copy of lemur, we still need to build and install all of the dependencies (including the build dependencies). I would rather not install unnecessary dependencies on something that hosts my PKI infrastructure. So instead of packaging it myself, it would make sense to have you guys package it once for everyone.

Obviously, this would not stop me from using lemur. It would just be a nice to have feature that would make it easier for others to use. (I wouldn't assume everyone would be willing to package lemur themselves.)

**Comment by kevgliss** [comment]
I haven't given up on this just yet. Will try to get a package up under the lemur-pki namespace.

**Comment by gugahoi** [comment]
I am almost sure you can overwrite versions in PyPi so long as you are the administrator of the repository. You might need some manual intervention for deleting the package within the UI and then pushing your own version but if memory serves me right, it should be possible.

**Comment by kevgliss** [comment]
The issue is that it rejects lower versions, Lemur is 0.5.0 but the previous package was 1.9. I have tried deleting the whole package from pypi but that didn't seem to work.

**Comment by jmcrawford45** [comment]
pypi is now up to date
