### ISSUE TITLE
Replacing multiple certs causes integrity error.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/lemur#743]
When creating a new cert, if you tell Lemur it will be replacing multiple certs, you get the following error:

> (psycopg2.IntegrityError) duplicate key value violates unique constraint "certificate_replacement_associations_ix" DETAIL: Key (certificate_id, certificate_id)=(XXXXX, XXXXX) already exists. [SQL: 'INSERT INTO certificate_replacement_associations (replaced_certificate_id, certificate_id) VALUES (%(replaced_certificate_id)s, %(certificate_id)s)'] [parameters: ({'replaced_certificate_id': YYYYY, 'certificate_id': XXXXX}, {'replaced_certificate_id': ZZZ, 'certificate_id': XXXXX})]

Either the UI should restrict the replace to a single cert or the DB model should support multiple.

**Comment by kevgliss** [comment]
This is caused by the following unique constraint:
https://github.com/Netflix/lemur/blob/master/lemur/migrations/versions/412b22cb656a_.py#L37

This shouldn't ever be triggered as the certificate creates a new id upon creation and is then associated. One possible explanation might be the way SQLAlchemy is evaluating the IDs, we might need to commit the certificate before attempting to associate the replaced certificates.
