### ISSUE TITLE
Synchronous issuer plugin design

### ISSUE THREAD

**Issue by treacher** [Netflix/lemur#755]
Recently we had an issue where NGINX timed out a request as it was taking longer than x seconds. When this happened, it created the certificate in Digicert but we lost the private key. In generally this is not ideal as you really want to store the private key as soon as you possibly can.

I have a proposal for an idea and I want to see what your thoughts are as to whether this is something you'd accept as a PR.

**Current workflow:**
CSR is created with Private Key -> Request made via IssuerPlugin to create/accept/retrieve certificate -> Store Certificate with Private key

**Proposed workflow**
CSR is created with Private Key -> Store Certificate in database with private key and no certificate
Sync cron runs -> Updates certificate

**Pros:**
- Asynchronous workflow
- You can't lose the private key
- You can now use approval workflows with your CA

**Cons:**
- If your request to the CA fails you have a certificate with only a private key in Lemur

**Comment by kevgliss** [comment]
I wouldn't have any problems merging something like this in as I think it is a very common workflow for low volume certificates, but it will take quite a bit of work. 

For historical context, most of our downstream clients and customers expect a response immediately such that they don't have to build in retry/fetching logic. We get around the asynchronous workflow by explicitly using APIs from CAs that are also synchronous (e.g. Digicert CIS). I don't know if that is an available to all customers.

I see two ways of adding this functionality:

**Workflow Option 1**
CSR is created with Private Key -> Request made via AsyncIssuerPlugin to create create/accept/retrieve certificate -> Task Status/Id is returned to caller -> Caller periodically checks for status. 

Components:
- Create a new plugin type that would be `AsyncIssuer`. All plugins of this type would use celery/rq to run a background process to request a certificate and then wait for it to be issued. 
- Create a new table to keep track of the certificate's private key and the current status of its issuance task.
- Modify certificate creation flow control, perhaps returning an empty certificate dictionary and task ID

**Workflow Option 2**
Create request -> Async? (Yes/No) -> Create background task -> return task id

Components:
- Make an explicit call to new endpoint `create/async` re-use existing plugins 
- Wrap the `create` function call in celery/rq background task.  

I'm not in love with either option, but I am currently leaning on Option 1.

**Comment by pjmichael** [comment]
Another intermediate Option we were considering was going from a single Certificate commit to a 2 stage commit. 
* The initial Certificate commit would contain the private key and any other data not derived from the cert_body & cert_chain.
* Following a successful request for creating a certificate, we would then update the Certificate with the returned cert body and chain.
* In the event of the request failing due to timeout, we won't have lost the private key and we'll have the ability to manually fix the entry without a certificate.

Currently if it fails we have to revoke the certificate and start again as we don't have the private key where as this approach gives us the ability to manually fix the certificate by fetching the details from the CA.

This may mean we'll need to change database constraints so I was wanting to check whether or not you thought this was a reasonable step in the right direction. I believe this will further enable us to move towards an async approach as well.

**Comment by kevgliss** [comment]
The two-stage approach could also work, but you might run into issues where the state of the certificate isn't clear. You have a private key, but the certificate failed for some reason. Do you retry within your plugin? Do you raise an error to have the user take an action? Either way, you have a nebulous private key without any associated metadata (CSR, domains, validity, etc.,). 

My preference would be an async implementation where the status of the task (issuance, destination, etc,.) is very clear and can be presented to the user is a straight forward way. This most likely means that the two-stage commit would indeed exist, but is tied to some other db table (tasks) and not to the certificate table itself.

**Comment by jchuong** [comment]
I also had this issue, and spent a little bit of time getting it mostly done (PR probably coming in the next few days, depending).  I'd like to have someone check and see if it makes sense once I do put it up.

Essentially:
1. Create cert as normal, if you get the response immediately, then you continue as normal
2. If you don't get a certificate from the issuing plugin, then you return empty cert body, chain and external_id. 
3. Then a PendingCertificate is created (PendingCertificate pretty much a subset of Certificate, with a couple extra fields such as renaming [certs are named based on certificate, which doesn't exist for Pending Certificate, so a dummy name needs to be generated in the meanwhile).
4. Then I use Sources sync to get the new certificates.  This has to be a Source because upon step 1, you have already ordered a certificate, trying to order again will result in a second certificate.  So you need to sync from sources.  Then for each certificate from source, I check for existing cert as before and update.  If the certificate doesn't exist, then check PendingCertificates for the order_id/external_id (this may depend of source), and create a certificate with PendingCertificate's fields. 
5.  Then delete the used PendingCertificate.  Update the count of syncs for every certificate (perhaps fail and notify if a PendingCert has sat around for too long).

This approach means you need a Source (will start pulling all existing certs from your CA, unless we want to filter by passing external_ids from Pending Certificates table to filter only Pending).  This also changes the relations quite a bit, as now you have pending certificates with the same relations as certificates, so that it can remap them once actually fulfilled.

Other considerations / to do on my side:
[] UI to view pending certificates
[] Checking roles / authorization to view, modify pending certs
[] Ability to cancel an order - pending cert can be cancelled on the CA, before it gets issued.  Need to update base plugins, and what happens if you cancel an order that was actually fulfilled but not yet synced.

**Comment by kevgliss** [comment]
How often do you plan to run the source plugins? We typically run them once per hour. I am also a little concerned with the Source plugin route. We have some issuers that have tens of thousands of certificates syncing them has become quite a problem, so much so that we've generally abandoned continuous syncing. 

> Create cert as normal, if you get the response immediately, then you continue as normal

Does this mean that support for pending certificate will be based on the plugin? Which issuer plugins are you focusing on? Are you planning async based issuer plugins.

**Comment by jchuong** [comment]
I plan on once an hour or less.  I haven't tried with a large source sync yet so I can't comment on the speed here.  We can definitely reverse the source sync to go through every pending certificate (which should be very few certificates), and try to see if the source has it or not.  This way, we just need another sync command (source pending-sync -s <plugin>).

>Does this mean that support for pending certificate will be based on the plugin? Which issuer plugins are you focusing on? Are you planning async based issuer plugins.

It shouldn't be based on any plugin, as long as they return empty certificate body in case of failure.  I am focusing on Digicert plugin.  In my case, most of the time certificates will be issued pretty much immediately, and I skip over the pending certificate route.  I'm not planning async based plugins because I don't want to change the expected flow / setup of current Lemur.  There's no way to know if one issuer will need async support or not.

**Comment by kevgliss** [comment]
@treacher and @jchuong Do either you have outstanding code for this? Internally it's might be more of a priority to have some sort of async support. Would like to understand if any of the above has been implemented.

**Comment by jchuong** [comment]
I have most of the code ready, I think (I haven't used it in production yet either...).  Still working through getting UI elements ready but I can show what I have already since the UI stuff is pretty low priority (ie, able to force update one cert via UI when the CLI will be used to update periodically).
