### ISSUE TITLE
Import TinyCA certificates and csr

### ISSUE THREAD

**Issue by arthurlogilab** [Netflix/lemur#786]
Hi first off : lemur looks awesome. Thanks for making and publishing this tool as open source. 

We are looking into migrating our certificates handled by TinyCA into lemur, is there a way to mass import certificates and requests from an existing project into lemur ? I haven't found a CLI that talks to the API so far, or a python binding ... could you point me in the right direction (or tell me it doesn't exist).

**Comment by kevgliss** [comment]
There is currently no direct support for migration of certs from any other CAs.

If you just want to migrate existing certificates into Lemur, the process should be relatively straightforward.

- Use the REST API [Docs](http://lemur.readthedocs.io/en/latest/developer/index.html#lemur.certificates.views.CertificatesUpload)
   - Full featured, allows you to upload/import/create certificates and bring them under Lemur's management.
- Write a 'Source' plugin [Docs](http://lemur.readthedocs.io/en/latest/developer/plugins/index.html#source)
   - If this will be an ongoing sync, source plugins allow you to pull in certificates from external sources periodically. 
- Write a CLI command [Source](https://github.com/Netflix/lemur/blob/master/lemur/certificates/cli.py#L149)
    - We don't currently have good documentation on creating commands and don't currently have an `upload` command, but it should be relatively trivial to create one using Lemur's internals. 

If you are looking to migrate TinyCA's root certificates into Lemur for additional issuances via the [cryptography](https://github.com/Netflix/lemur/blob/f91ae5b319f0665524dd465dc8c9c4fb7f0773dc/lemur/plugins/lemur_cryptography/plugin.py) plugin the path is a bit less clear. 

Essentially you can still do this via the CLI or the REST API but instead of using the `certificates` endpoint or service you would use the `authorities` endpoint or service.

**Comment by arthurlogilab** [comment]
@kevgliss thanks for your detailed answer. We're starting to "really" use lemur at our company so it is probable we will develop (and contribute) some code to do this.

**Comment by JoCriSem** [comment]
@kevgliss has there been any development since in supporting some kind of mass import of certificates?

**Comment by kevgliss** [comment]
Not that I know of. cc @castrapel
