### ISSUE TITLE
Support for LDAP Bind User?

### ISSUE THREAD

**Issue by SecurityInsanity** [Netflix/lemur#907]
We're looking to integrate Lemur with our LDAP setup (instead of using basic auth), and looking at the configuration: [HERE](http://lemur.readthedocs.io/en/latest/administration.html#ldap-options) I'm not able to see a way to specify a bind user. Is this not currently supported in lemur, or is there an option I'm missing?

**Comment by pr8kerl** [comment]
Lemur uses the login credentials of the person trying to authenticate to bind to the ldap service. If ldap bind is successful, then obviously the ldap username/password combination provided are valid. Lemur then looks at the different ldap groups a user is a member of to determine whether access should be granted.

**Comment by SecurityInsanity** [comment]
So I worded this incorrectly, and I'm sorry.

Essentially we have users type in sAMAAccountNames (`ecoan` in my case), but obviously we need the full DN to authenticate. So we have a Service Account that is generated so we can look up the full DN of the User. I'm essentially looking at how I can authenticate with that user to perform those lookups.

**Comment by pr8kerl** [comment]
No probs. Perhaps I misunderstood.

So you're using AD which is good - because I've only tested against AD. :)

The lemur ldap module uses the user principal name (upn) of the authenticating user to bind. This is done once for each user at login time. The UPN is effectively the email address in AD/LDAP of the user. If the user doesn't provide the email address, it constructs one based on the username supplied (which should normally match the samAccountName) and the value provided by the config LDAP_EMAIL_DOMAIN.
The config LDAP_BASE_DN tells lemur where to search within the AD/LDAP tree for the given UPN (user). If the bind with those credentials is successful - there is a valid user in AD with correct password.
So no other bind user is necessary for authentication. Lemur just uses the upn (or samAccountName and constructs a upn) and the user supplied password.

My lemur config for ldap looks similar to this:
```
LDAP_AUTH = True
LDAP_BIND_URI='ldaps://domaincontroller.evilcorp.net'
LDAP_BASE_DN='DC=users,DC=evilcorp,DC=net'
LDAP_EMAIL_DOMAIN='evilcorp.com'
LDAP_USE_TLS = True
LDAP_CACERT_FILE = '/opt/app/lemur/cacerts'
LDAP_REQUIRED_GROUP = 'certificate-management-access'
LDAP_GROUPS_TO_ROLES = {'certificate-management-admin': 'admin', 'certificate-management-read-only': 'read-only'}

LEMUR_DEFAULT_ROLE="operator"
```

So once Lemur is configured similarly and has network connectivity to the server/port defined in LDAP_BIND_URI, you should be good. Try logging in with your email address and valid password.

Perhaps I should update the docs to make this clearer.
Hope this helps and makes sense. Shout out  if it doesn't.

**Comment by SecurityInsanity** [comment]
Didn't realize I hadn't closed this! This does indeed work for us, Thanks much!
